name: ci-cd

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy on server
        uses: appleboy/ssh-action@v1.0.0
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          port: ${{ secrets.VPS_SSH_PORT }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: BOT_TOKEN
          debug: true
          script: |
            docker login ghcr.io -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}
            docker system prune -f
            cd ${{ vars.VPS_PROJECT_PATH }}
            docker compose -f ./docker-compose.prod.yml -p bot pull
            docker compose -f ./docker-compose.prod.yml -p bot up -d