name: ci-cd

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & deploy bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
      
      - name: Copy docker-compose on sever
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          port: ${{ secrets.VPS_SSH_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          username: ${{ secrets.VPS_SSH_USER }}
          rm: true
          source: docker-compose.prod.yml
          target: ${{ vars.VPS_PROJECT_PATH }}

      - name: Run deploy on server
        uses: appleboy/ssh-action@v1.0.0
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          port: ${{ secrets.VPS_SSH_PORT }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: BOT_TOKEN
          debug: true
          script: |
            docker login ghcr.io -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}
            docker-compose -f ${{ vars.VPS_PROJECT_PATH }}/docker-compose.prod.yml -p bot pull
            docker-compose -f ${{ vars.VPS_PROJECT_PATH }}/docker-compose.prod.yml -p bot up -d